### ISSUE TITLE
Can make using simple sort method

### ISSUE THREAD

**Issue by basava1134** [basava1134/First-PR-Hacktoberfest#76]
[String Reverse](https://github.com/basava1134/First-PR-Hacktoberfest/blob/main/C%20languages/reverse_string.c)

**Comment by MrAnonymous09** [comment]
@basava1134 Please assign it to me

**Comment by MrAnonymous09** [comment]
Yes Updated!

**Comment by basava1134** [comment]
Thanks! don't hesitate to give us a star
